import { ApiProperty, ApiPropertyOptional } from "@nestjs/swagger";
import {
  ValidateNested,
  IsNotEmpty,
  Matches,
  IsOptional,
  IsBoolean,
} from "class-validator";
import { Type } from "class-transformer";
import { ForwardRequestDto } from "./forward-request.dto";

/**
 * Gasless Transaction Request DTO
 * Complete API request structure including ForwardRequest and signature
 *
 * SPEC-GASLESS-001: Gasless Transaction API
 * - U-GASLESS-001: EIP-712 Signature Verification
 * - T-GASLESS-003: DTO Validation
 */
export class GaslessTxRequestDto {
  /**
   * ForwardRequest structure (EIP-712 typed data)
   * Contains all transaction details that were signed
   */
  @ApiProperty({
    description: "ForwardRequest structure",
    type: ForwardRequestDto,
  })
  @ValidateNested()
  @Type(() => ForwardRequestDto)
  @IsNotEmpty()
  request: ForwardRequestDto;

  /**
   * EIP-712 signature
   * The signature of the typed ForwardRequest data
   * Generated by the client using ethers.signTypedData()
   * Format: 0x + 130 hex characters (65 bytes: r=32, s=32, v=1)
   * Example: 0x1234...
   */
  @ApiProperty({
    description: "EIP-712 signature (0x + 130 hex chars)",
    example:
      "0x1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef1c",
  })
  @Matches(/^0x[a-fA-F0-9]{130}$/, {
    message: "Signature must be 0x followed by 130 hex characters (65 bytes)",
  })
  signature: string;

  /**
   * SPEC-DLQ-001: DLQ retry strategy (optional)
   * Controls whether DLQ Consumer should attempt reprocessing
   * - true: Attempt reprocessing when message reaches DLQ
   * - false/undefined: Mark as failed immediately (default behavior)
   * U-3: MUST be backward compatible (field is optional)
   * UN-4: MUST NOT break compatibility with existing clients
   */
  @ApiPropertyOptional({
    description: "Enable retry when transaction reaches DLQ (default: false)",
    example: false,
  })
  @IsOptional()
  @IsBoolean()
  retryOnFailure?: boolean;
}
